Book store develop
StoneBlood-bit/book-store pull request #6
Opened 2024-12-11 15:36 UTC by StoneBlood-bit

2024-12-11 19:06 UTC, Elena-Bruyako requested changes
see comments

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/AuthenticationController.java
> +@RequestMapping(value = "/auth")
```suggestion
@RequestMapping("/auth")
```

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/mapper/UserMapper.java
> +    @Mapping(target = "shippingAddress", source = "shippingAddress")
```suggestion
```

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/User.java
> +@Data
```suggestion
@Getter
@Setter
```

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/UserServiceImpl.java
> +        if (userRepository.findByEmail(requestDto.getEmail()).isPresent()) {
```suggestion
        if (userRepository.existsByEmail(requestDto.getEmail())) {
```

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/UserServiceImpl.java
> +        User user = new User();
use mapper

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/UserServiceImpl.java
> +        return userMapper.toUserResponse(savedUser);
```suggestion
        userRepository.save(user);
        return userMapper.toUserResponse(user);
```

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: firstName
```suggestion
                  name: first_name
```

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: lastName
```suggestion
                  name: last_name
```

2024-12-11 19:06 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  name: shippingAddress
```suggestion
                  name: shipping_address
```

2024-12-12 07:34 UTC, liliia-ponomarenko approved these changes
Good job! 👍

2024-12-12 07:34 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: varchar(255)
add one empty line

2024-12-12 12:13 UTC, merged