added entity `Category`
StoneBlood-bit/book-store pull request #9
Opened 2024-12-21 18:24 UTC by StoneBlood-bit

2024-12-22 18:26 UTC, Elena-Bruyako requested changes
see comments

2024-12-22 18:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/controller/CategoryController.java
> +@RequestMapping(value = "/categories")
```suggestion
@RequestMapping("/categories")
```

2024-12-22 18:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/dto/book/CreateBookRequestDto.java
> +    private List<Long> categoryIds;
let's add validation

2024-12-22 18:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/model/Category.java
> +@Data
Don't use `@Data` for entities, find articles to read about problems

2024-12-22 18:26 UTC, Elena-Bruyako commented on src/main/java/mate/academy/service/category/CategoryServiceImpl.java
> +                .collect(Collectors.toList());
```suggestion
                .toList();
```

2024-12-23 07:26 UTC, liliia-ponomarenko approved these changes
Good job! A few minor comments but please fix them before merging ;)

2024-12-23 07:26 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/repository/BookRepository.java
> +    List<Book> findByCategories_Id(Long categoryId);
```suggestion
    List<Book> findByCategoriesId(Long categoryId);
```

2024-12-23 07:26 UTC, liliia-ponomarenko commented on src/main/java/mate/academy/service/category/CategoryService.java
> +    List<BookDtoWithoutCategoryIds> getBooksByCategoryId(Long id);
better move it to BookService

2024-12-23 12:59 UTC, merged